################################
//get server
GET http://localhost:3000/

################################
//get api vclaim
GET http://localhost:3000/vclaim

###############################
//vclaim1.1 dvlp get diagnosa
GET http://localhost:3000/vclaim/diagnosa/A08.5

################################
//vclaim1.1 dvlp get diagnosa
GET http://localhost:3000/vclaim/poli/ICU

################################
//vclaim1.1 dvlp faskes
GET http://localhost:3000/vclaim/faskes/kalijaga/2

################################
//get api antrian
GET http://localhost:3000/antrian

################################
//get api aplicare
GET http://localhost:3000/aplicare







###############################
//antreanv2 dvlp get ref poli
GET http://localhost:3000/antri-poli

###############################
//antreanv2 dvlp get dokter
GET http://localhost:3000/antri-jadwal/kodepoli/UMU/tanggal/2021-08-01